### ISSUE TITLE
EndWavePopup

### ISSUE THREAD

**Issue by fischli97** [Sajohn-CH/Spielprojekt#18]
Spiel überspringt eine Welle, wenn man etwas kauft

**Comment by Sajohn-CH** [comment]
Konnte diesen Fehler nicht reproduzieren. Dagegen stüzt Spiel häufiger ab, wenn man auf nächste Welle klickt. Es scheint ein Fehler im InputSystem zu sein

**Comment by Sajohn-CH** [comment]
Das Spiel scheint abzustürzen wenn man den Turm upgradet und danach auf den nextWave-Button im endWavePopup klickt

**Comment by Sajohn-CH** [comment]
Fehler gefunden und behoben :)
