### ISSUE TITLE
Türme verbessern

### ISSUE THREAD

**Issue by Sajohn-CH** [Sajohn-CH/Spielprojekt#2]
Andere Türme unterschiedlicher machen. Z.B. einer der alle Bomben verlangsamt.

**Comment by fischli97** [comment]
Eine Zweite Turmart wurde hinzugefügt (Zieht Geschwindigkeit statt Leben ab.)

**Comment by fischli97** [comment]
Idee für die dritte Turmart: Wandelt schiessende Bomben zu normalen um.

**Comment by fischli97** [comment]
Dritte Turmart implementiert
