### ISSUE TITLE
Steuerung auf was Türme schiesen. 

### ISSUE THREAD

**Issue by Sajohn-CH** [Sajohn-CH/Spielprojekt#31]
Ob sie immer auf die erste Bombe, die schwächste, die erste ShootingBombs etc.

**Comment by fischli97** [comment]
auf 1. Bombe, 1. ShootingBomb, schwächste Bombe, stärkste Bombe methoden bereitgestellt

**Comment by fischli97** [comment]
auch auf weiteste Bombe implementiert. Kann im upgrademenu ausgewählt werden

**Comment by fischli97** [comment]
Auch nur auf shootingBombs oder normale Bomben (oder alle) möglich
