### ISSUE TITLE
Informationen zum Turm

### ISSUE THREAD

**Issue by fischli97** [Sajohn-CH/Spielprojekt#32]
Informationen zum Turm darüber, falls man darauf zeigt. Level (unt evt Lebensbalken) des Turmes immer anzeigen.

**Comment by Sajohn-CH** [comment]
Der Lebensbalken und Level ist sichtbar sobal man auf den Turm schaut, wobei es nicht direkt über dem Turm eingeblendet wird, sondern einfach in der Mitte des Bildschirm (wo in etwa auch der Turm steht).

**Comment by fischli97** [comment]
Nicht mehr über jede Entfernung und durch den Beacon sichtbar. Auch wurde das Fadenkreuz beim anzeigen entfernt

**Comment by fischli97** [comment]
Warnung in form eines roten Ausrufezeichens über dem Turm sichtbar, falls das Leben unter 20% fällt

**Comment by fischli97** [comment]
Level über dem Turm angezeigt. Warnung, wenn das Leben unter 20% fällt jetzt durch die rote Einfärbung der Zahl.

**Comment by Sajohn-CH** [comment]
Zahl erscheint nicht dreidimensional. Ich sehe sie nie von der Seite.

**Comment by fischli97** [comment]
Sie wird immer zum Spieler gedreht, da sie sonst missverstanden werden könnte. IV und VI würden verwechselt
